# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-08-31 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_authority_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.Password'),
        ),
    ]
